DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL
);

INSERT INTO
    users (login, password_hash)
VALUES
    ('nikita', MD5('m5bg8'));

SELECT
    *
FROM
    users;