DROP TABLE IF EXISTS records;

CREATE TABLE records (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_login TEXT NOT NULL REFERENCES users,
    content TEXT NOT NULL
);

INSERT INTO
    records (user_login, content)
SELECT
    login,
    'Hello, World!'
FROM
    users
LIMIT
    1;

SELECT
    *
FROM
    records;