DROP TABLE IF EXISTS records CASCADE;

CREATE TABLE records (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO
    records (user_id, content)
SELECT
    users.id,
    'Hello, World!'
FROM
    users
WHERE
    login LIKE 'nikita'
LIMIT
    1;

SELECT
    *
FROM
    records;